### ISSUE TITLE
@keyframes dont work

### ISSUE THREAD

**Issue by iLightGit** [myfreeweb/cssprefixer#41]
input 

@keyframes window-light {
	0% {opacity: 0.3}
	20% {opacity: 0.4}
	50% {opacity: 0.3}
	70% {opacity: 0.5}
	80% {opacity: 0.3}
	90% {opacity: 0.4}
	100% {opacity: 0.3}
}

output

<pre>Traceback (most recent call last):
  File &quot;/base/data/home/runtimes/python/python_lib/versions/1/google/appengine/ext/webapp/_webapp25.py&quot;, line 717, in __call__
    handler.post(*groups)
  File &quot;/base/data/home/apps/cssprefixer/1.358346175691989048/main.py&quot;, line 42, in post
    res = cssprefixer.process(orig, minify=False)
  File &quot;/base/data/home/apps/cssprefixer/1.358346175691989048/cssprefixer/engine.py&quot;, line 101, in process
    cssText = magic(ruleset, debug, minify, filt, parser)
  File &quot;/base/data/home/apps/cssprefixer/1.358346175691989048/cssprefixer/engine.py&quot;, line 25, in magic
    inner = parser.parseString(re.split(r'@keyframes\s?\w+\s?{(.*)}', ruleset.cssText.replace('\n', ''))[1])
IndexError: list index out of range
</pre>

**Comment by myfreeweb** [comment]
This is because of the `-` in `window-light`, see the regexp in the traceback.

This project isn't maintained anymore, try [autoprefixer](https://github.com/postcss/autoprefixer).
